ServerRoot "/etc/apache2"
PidFile "/var/run/apache2/apache2.pid"
Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5

User www-data
Group www-data

HostnameLookups Off
ServerName localhost

# Load modules
LoadModule mpm_event_module /usr/lib/apache2/modules/mod_mpm_event.so
LoadModule authz_core_module /usr/lib/apache2/modules/mod_authz_core.so
LoadModule authz_host_module /usr/lib/apache2/modules/mod_authz_host.so
LoadModule mime_module /usr/lib/apache2/modules/mod_mime.so
LoadModule dir_module /usr/lib/apache2/modules/mod_dir.so
LoadModule log_config_module /usr/lib/apache2/modules/mod_log_config.so
LoadModule alias_module /usr/lib/apache2/modules/mod_alias.so

AccessFileName .htaccess

<FilesMatch "^\.ht">
    Require all denied
</FilesMatch>

LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %b" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
LogFormat "%{X-Forwarded-For}i %h %l %u %t \"%r\" %>s %b \"%{User-Agent}i\"" custom

CustomLog "/var/log/apache2/access.log" custom
ErrorLog "/var/log/apache2/error.log"
LogLevel warn

Listen 80

DocumentRoot "/var/www/html"
<Directory />
    AllowOverride None
    Require all denied
</Directory>

<Directory /var/www/html>
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

DirectoryIndex index.html
