version: '3.8'

services:
  apache-target:
    build: ./apache
    container_name: apache-target
    ports:
      - "8080:80"
    volumes:
      - ./logs/apache:/var/log/apache2

  iis-target:
    build: ./iis-nginx
    container_name: iis-target
    ports:
      - "8081:80"
    volumes:
      - ./logs/iis:/var/log/nginx

  redis-store:
    image: redis:alpine
    container_name: redis-store
    ports:
      - "6379:6379"
